apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: tecopos-observability
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        uid: loki-tecopos
        url: http://loki.tecopos-observability.svc.cluster.local:3100
        isDefault: true
        editable: false
        jsonData:
          timeout: 60
          maxLines: 5000

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'tecopos-observability'
        orgId: 1
        folder: 'TECOPOS'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
